### ISSUE TITLE
Hi, Patrick

### ISSUE THREAD

**Issue by hakkatil** [paystory-de/thermal-printer-cordova-plugin#1]
Do you have a quick example file about how to test this plugin? 
I used the TCP Code Example on this page https://github.com/DantSu/ESCPOS-ThermalPrinter-Android
but it seems that it is not doing anything, no errors or warnings.
Thank you

**Comment by ishak-lm** [comment]
Send your code over here please

**Comment by patrickbussmann** [comment]
Yes @hakkatil send us your example code.
In my example the printer is printing.
