### ISSUE TITLE
simple code in JavaScript project cordova

### ISSUE THREAD

**Issue by aliayoubi** [paystory-de/thermal-printer-cordova-plugin#11]
hi 
can you send me a simple code that work in java script project cordova
thank alot

**Comment by patrickbussmann** [comment]
Please check if this is working for you:
https://github.com/paystory-de/thermal-printer-cordova-plugin/issues/15#issuecomment-1128100770
https://github.com/paystory-de/thermal-printer-cordova-plugin/issues/9#issuecomment-993658943

**Comment by devlas-cl** [comment]
I think it means that it needs javascript code that works, since the example is only in typescript. For example, how to import the plugin, and use the basic functions in js.
