### ISSUE TITLE
How to use  ESC/POS commands And  getNbrCharactersPerLine() ,getPrinterWidthMM() , getPrinterDpi() and other method

### ISSUE THREAD

**Issue by rajeshsolankijodhpur** [paystory-de/thermal-printer-cordova-plugin#12]
hi patrickbussmann
i am using your paystory-de/thermal-printer-cordova-plugin
URL https://github.com/paystory-de/thermal-printer-cordova-plugin
i use all the function on document and all are work find
can you provide any document or any other link to
get getNbrCharactersPerLine() ,getPrinterWidthMM() , getPrinterDpi() and other method
how i get these thing in my application

and how i use ESC/POS commands (https://www.sparkag.com.br/wp-content/uploads/2016/06/ESC_POS-AK912-English-Command-Specifications-V1.4.pdf)

**Comment by patrickbussmann** [comment]
Hi @rajeshsolankijodhpur,

Here we only using the library: https://github.com/DantSu/ESCPOS-ThermalPrinter-Android
So when you want a function to `getNbrCharactersPerLine`, `getPrinterWidthMM` or `getPrinterDpi` then you must make an feature request here: https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/issues/new

Thank you.

**Comment by rajeshsolankijodhpur** [comment]
thank's for your reply & precious time  dear
i need some help regarding this plugin if you help me it will great for me
dear.
when i use default function
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android  according to your
document
text and other thing not cover full page width it's takes 70% printing area
how i achieve full width
i have attached a printed format  (comapny name / address not occupy full
width ) add code also
var text=
"[C]<font size='big'>COMPANY NAME</font>"+
"[C]<u><font size='normal' width='100'>COMPANY ADDRESS</font></u>"+
"[L]<b>KOT NO:</b>1[R]<b>Date/Time:</b>00/00/0000 00:00"+
"[L]<b>Table:</b>TABLE NO[R]<b>Waiter:</b>WAITER NAME"+
"<b width='60'>Product Name</b><b width='40'>Qty</b>"+
"<font size='normal'>Item1 </font><font size='normal'>1</font>"+
"<font size='normal'>Item2 </font><font size='normal'>1</font>"+
"<font size='normal'>Item3 </font><font size='normal'>4</font
[image: IMG20220129184501.jpg]
