### ISSUE TITLE
Charset Encoding ?

### ISSUE THREAD

**Issue by uokivan** [paystory-de/thermal-printer-cordova-plugin#13]
Hi @patrickbussmann

This is a  great plugin.

Can we Charset Encoding ?
Hope can print word in Traditional Chinese.

Thank you very much

**Comment by uokivan** [comment]
I change the code from "ThermalPrinterCordovaPlugin.java" :

From :
charsetEncodingData.optString("charsetName", "windows-1252"),

To:
charsetEncodingData.optString("charsetName", "GBK"),

However, when I check the encoding by getEncoding(),
the  encoding still is "windows-1252"........

**Comment by patrickbussmann** [comment]
What printer are you using?
Sometimes you must configure it a bit separate.
I had a printer where I had a separate software for setting up the charset before I was able to print with it.
