### ISSUE TITLE
how to reconnect printer before print?

### ISSUE THREAD

**Issue by rizwanbao** [paystory-de/thermal-printer-cordova-plugin#18]
how we can connect printer before print for avoiding connection reset and broken pipe issue like if there is any way to calling this private EscPosPrinter getPrinter(CallbackContext callbackContext, JSONObject data) i think problem will be solved

**Comment by patrickbussmann** [comment]
Disconnect -> https://github.com/paystory-de/thermal-printer-cordova-plugin#disconnectprinterdata-successcallback-errorcallback

**Comment by JuanFCVal** [comment]
When should I disconnect the printer? If I disconnect after printing I'm unable to print again later. 😕
