### ISSUE TITLE
when print bitmap return function of success but nothing printed

### ISSUE THREAD

**Issue by ZarooDotnet** [paystory-de/thermal-printer-cordova-plugin#19]
i convert image to base64 then use it in bitmap function like :
ThermalPrinter.bitmapToHexadecimalString({
          type: 'tcp',
          address: '192.168.1.100',
          port: 9100,
          id: '192.168.1.100:9100', // Use an unique identifier for each printer i. e. address:port or name
          base64:imageData
         }, function () {
          console.log('Successfully printed!');
        }, function (error) {
          console.error('Printing error', error);
        });

**Comment by patrickbussmann** [comment]
Can you please use this code:
https://github.com/paystory-de/thermal-printer-cordova-plugin/issues/15#issuecomment-1128100770

Because `bitmapToHexadecimalString` gives you only the string. You need to print it afterwards.
See the link above then you know what I mean 😊
