### ISSUE TITLE
listPrinters is not defined

### ISSUE THREAD

**Issue by Phanusone** [paystory-de/thermal-printer-cordova-plugin#2]
Hello, i using this plugin in my project use framework7-vue. Now i have an error= "listPrinters is not defined"
this is test code:
methods: {
    login: function () {
      listPrinters(
        "bluetooth",
        function (s) {
          console.log("OK",s);
        },
        function (r) {
          console.log("Err" + r);
        }
      );
    },
    }

**Comment by patrickbussmann** [comment]
Because (window).listPrinters is not defined 😅
Try `ThermalPrinterPlugin.listPrinters` or `ThermalPrinter.listPrinters` instead.
Or if both not exists then try something with `Cordova.plugins....`.
You can import the thermal-printer.js, too.
