### ISSUE TITLE
Printer images Fix width for 100% ?

### ISSUE THREAD

**Issue by mounoydev** [paystory-de/thermal-printer-cordova-plugin#3]
Hi
Can i fix width 100% of paper,
It looks like with not fix when i try to change height 
I try to fix the size of canves,  width 1000px
 height Auto(by the Image,)
But when print width not full of paper

**Comment by patrickbussmann** [comment]
I think your issue is not related on this plugin.
Its a thing for the base (wrapped) library: https://github.com/DantSu/ESCPOS-ThermalPrinter-Android
Can you open your issue there please?
