### ISSUE TITLE
Missing permission for android.permission.DISABLE_KEYGUARD

### ISSUE THREAD

**Issue by arpitraykar** [paystory-de/thermal-printer-cordova-plugin#37]
Hi We have updates the ionic capacitor 4 app to maxSdkVersion 32. Now we are facing this error Missing permission for android.permission.DISABLE_KEYGUARD

As per the official document we need to change to this "If you want your device to be communicable with other devices, you must add [BLUETOOTH_CONNECT](https://developer.android.com/reference/android/Manifest.permission#BLUETOOTH_CONNECT) permission."

So we have made the below changes in AndroidManifest.xml file but no use.

    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH" />

**Comment by saaiful** [comment]
@arpitraykar Did you solve it? Same issue with my app too. 

@DantSu Andorid SDK 30+ requires user approved permission for `,BLUETOOTH_CONNECT,` and `BLUETOOTH_SCAN`, please look into it.

**Comment by DantSu** [comment]
https://github.com/DantSu/ESCPOS-ThermalPrinter-Android/blob/master/app/src/main/AndroidManifest.xml yes and it's done for more than a year....

**Comment by saaiful** [comment]
@DantSu `user approved permission` 
https://developer.android.com/guide/topics/connectivity/bluetooth/permissions
![image](https://user-images.githubusercontent.com/4525049/226319389-ead630f4-b565-4267-8a3e-5e586e0a57c4.png)

**Comment by DantSu** [comment]
No PR is needed. I don't know what you wan't. But don't include me in your issue, the Android JAVA library is correct. It's not to the library to do the request permission because some use don't want bluetooth and just USB or LAN. So you have to it by yourself according to your needs.

**Comment by saaiful** [comment]
I created a new method for asking for user grantable permission, updated the main android apk version (https://github.com/DantSu/ESCPOS-ThermalPrinter-Android) 
https://github.com/saaiful/thermal-printer-cordova-plugin

It works, but need few updates. I will hopefully fix those.

**Comment by patrickbussmann** [comment]
@saaiful maybe you can create a pull request so that we have one main repository and not too many forks 🙂
Would be awesome and help everyone 🥳

**Comment by saaiful** [comment]
> @saaiful maybe you can create a pull request so that we have one main repository and not too many forks 🙂 Would be awesome and help everyone 🥳

Working on some possible issue , after that will create pull request

**Comment by saaiful** [comment]
New PR added
https://github.com/paystory-de/thermal-printer-cordova-plugin/pull/39

**Comment by jaco** [comment]
Unfortunately I still get `Missing permission for android.permission.DISABLE_KEYGUARD` while trying to print and `Missing permission for android.permission.BLUETOOTH` while trying to list printers.

Method `requestBTPermissions` is successful but the result object is `{"BLUETOOTH":false,"BLUETOOTH_ADMIN":false,"BLUETOOTH_SCAN":false,"granted":true,"BLUETOOTH_CONNECT":true}`

**Comment by jaco** [comment]
listPrinters method checks for `android.permission.BLUETOOTH` without checking api version like requestBTPermissions to - so it can't work. Skipping permission check and list works...

**Comment by jaco** [comment]
I have found another bad check:

```            if (!this.cordova.hasPermission(Manifest.permission.BLUETOOTH)) {
                callbackContext.error(new JSONObject(new HashMap<String, Object>() {{
                    put("error", "Missing permission for " + Manifest.permission.DISABLE_KEYGUARD);
                }}));
                return null;
            }
```

This the reason… 

After removing this its finally works! :)

**Comment by danielehrhardt** [comment]
> I have found another bad check:
> 
> ```
>                 callbackContext.error(new JSONObject(new HashMap<String, Object>() {{
>                     put("error", "Missing permission for " + Manifest.permission.DISABLE_KEYGUARD);
>                 }}));
>                 return null;
>             }
> ```
> 
> This the reason…
> 
> After removing this its finally works! :)

Can you open a PR?

**Comment by bobolat** [comment]
@saaiful can this plugin work with ionic capacitor? i have this error while requestBTpermission

`Unable to find a Capacitor plugin to handle permission requestCode, trying Cordova plugins 4`

can help me?
