### ISSUE TITLE
App Crash whenever i call print function

### ISSUE THREAD

**Issue by promisefemi** [paystory-de/thermal-printer-cordova-plugin#4]
Hello, thanks for the library but i haven't been able to make it work, i am printing with TCP.
I pass all necessary fields, but it keeps crashing but if i take out the ID property from the data object, i doesn't crash but i get an error telling me to pass the ID but when i do the app crashes.

[App crash only happens when i call the function]

`
function requestPermission() {
  var IPAddress = "192.168.1.240";
  var port = 9100;
  console.log(IPAddress, port);
  if (ThermalPrinter.printFormattedText) {
    ThermalPrinter.printFormattedTextAndCut(
      {
        type: "tcp",
        id: "192.168.1.240:9100", // i have also tried "192.168.1.2409100
        address: IPAddress,
        port: port,
      },
      function (success) {
        console.log(success, "SUCCESS");
      },
      function (error) {
        console.log(error, "ERROR");
      }
    );
  }
}
`

Thanks.

**Comment by patrickbussmann** [comment]
Thanks for reporting.
Its fixed now in 1.0.6 -> https://github.com/paystory-de/thermal-printer-cordova-plugin/commit/fb9d8ff65683380811eee2b5f4c7a720a8cd22ec

**Please use this command:**
```
function requestPermission() {
    var IPAddress = "192.168.1.240";
    var port = 9100;
    console.log(IPAddress, port);
    if (ThermalPrinter.printFormattedText) {
        ThermalPrinter.printFormattedTextAndCut({
            type: "tcp",
            id: "192.168.1.240:9100", // ID can be also "myprinter" or "lan-printer" or something useful
            address: IPAddress,
            port: port,
            text: 'Its working now'
        }, function (success) {
            console.log(success, "SUCCESS");
        }, function (error) {
            console.log(error, "ERROR");
        });
    }
}
```
