### ISSUE TITLE
Cordova build crash on cordova android 10.0.1

### ISSUE THREAD

**Issue by clarklight** [paystory-de/thermal-printer-cordova-plugin#6]
Hi, i need some help here, i tried to build the app with the plugin, and the build failed with many lines of error saying there are duplicate classes. I am building this on android 10.0.1 targetSDKversion 30. Would this be anything to do with the androidX update? Because i tried to update the app onto playstore and the min target version is 30, which requires the android 10.0.1

Below is part of the build error. 

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.zxing.BarcodeFormat found in modules jetified-barcodescanner-release-2.1.5-runtime (:barcodescanner-release-2.1.5:) and jetified-core-3.4.0 (com.google.zxing:core:3.4.0)

Thanks! 
Clark

**Comment by patrickbussmann** [comment]
Hi Clark,

as your error show, please ask your barcode scanner plugin maintainer.
Or can you show us your package.json with all the plugins you're working with?

We must be able to reproduce the issue.
Thanks.
