### ISSUE TITLE
I'll check soon but do you have example code so that I can fix it quicker than without?

### ISSUE THREAD

**Issue by joaquinPublyland** [paystory-de/thermal-printer-cordova-plugin#9]
I have the same problem, the console says that it is not defined. My example code so you can review. Maybe I'm not doing it right.

declare var ThermalPrinterCordovaPlugin: any;

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {

  constructor(
  ) {
    const localPrinter = new ThermalPrinterCordovaPlugin();

    var text =
    "[L]\n" +
                    "[C]<u><font size='big'>ORDER N°045</font></u>\n" +
                    "[L]\n" +
                    "[C]================================\n" +
                    "[L]\n" +
                    "[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
                    "[L]  + Size : S\n" +
                    "[L]\n" +
                    "[L]<b>AWESOME HAT</b>[R]24.99e\n" +
                    "[L]  + Size : 57/58\n" +
                    "[L]\n" +
                    "[C]--------------------------------\n" +
                    "[R]TOTAL PRICE :[R]34.98e\n" +
                    "[R]TAX :[R]4.23e\n" +
                    "[L]\n" +
                    "[C]================================\n" +
                    "[L]\n" +
                    "[L]<font size='tall'>Customer :</font>\n" +
                    "[L]Raymond DUPONT\n" +
                    "[L]5 rue des girafes\n" +
                    "[L]31547 PERPETES\n" +
                    "[L]Tel : +33801201456\n" +
                    "[L]\n" +
                    "[C]<barcode type='ean13' height='10'>831254784551</barcode>\n" +
                    "[C]<qrcode size='20'>http://www.developpeur-web.dantsu.com/</qrcode>";

    var data = {
      type: "tcp",
      id: '192.168.1.99:9100',
      address: '192.168.1.99',
      port: '9100',
      mmFeedPaper: '200',
      dotsFeedPaper: '20',
      text: text

    };
    localPrinter.printFormattedTextAndCut(data, function(){
      console.log( "IMPRESO CORRECTAMENTE");
    }, function(){
      console.log( "EROORRRR AL IMPRIMIR");
    })
  }

}

And this is error in console
E/Capacitor/Console: File: http://localhost/vendor.js - Line 60755 - Msg: ERROR Error: Uncaught (in promise): ReferenceError: ThermalPrinterCordovaPlugin is not defined
    ReferenceError: ThermalPrinterCordovaPlugin is not defined
        at new HomePage (http://localhost/pages-home-home-module.js:128:30)
        at NodeInjectorFactory.HomePage_Factory [as factory] (ng:///HomePage/ɵfac.js:4:10)
        at getNodeInjectable (http://localhost/vendor.js:58141:44)
        at instantiateRootComponent (http://localhost/vendor.js:64681:23)
        at createRootComponent (http://localhost/vendor.js:66988:23)
        at ComponentFactory$1.create (http://localhost/vendor.js:79631:25)
        at ViewContainerRef.createComponent (http://localhost/vendor.js:77671:47)
        at IonRouterOutlet.activateWith (http://localhost/vendor.js:49725:53)
        at ActivateRoutes.activateRoutes (http://localhost/vendor.js:103923:40)
        at http://localhost/vendor.js:103874:18

**Comment by patrickbussmann** [comment]
I'll add some examples soon. Sorry.

Your file should look like:

```
import {Component} from '@angular/core';
import {ThermalPrinterPlugin} from 'thermal-printer-cordova-plugin/src';

declare let ThermalPrinter: ThermalPrinterPlugin;

@Component({
  selector: 'app-home',
  templateUrl: 'home.page.html',
  styleUrls: ['home.page.scss'],
})
export class HomePage {
  constructor() {
    var text =
      '[L]\n' +
      '[C]<u><font size=\'big\'>ORDER N°045</font></u>\n' +
      '[L]\n' +
      '[C]================================\n' +
      '[L]\n' +
      '[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n' +
      '[L]  + Size : S\n' +
      '[L]\n' +
      '[L]<b>AWESOME HAT</b>[R]24.99e\n' +
      '[L]  + Size : 57/58\n' +
      '[L]\n' +
      '[C]--------------------------------\n' +
      '[R]TOTAL PRICE :[R]34.98e\n' +
      '[R]TAX :[R]4.23e\n' +
      '[L]\n' +
      '[C]================================\n' +
      '[L]\n' +
      '[L]<font size=\'tall\'>Customer :</font>\n' +
      '[L]Raymond DUPONT\n' +
      '[L]5 rue des girafes\n' +
      '[L]31547 PERPETES\n' +
      '[L]Tel : +33801201456\n' +
      '[L]\n' +
      '[C]<barcode type=\'ean13\' height=\'10\'>831254784551</barcode>\n' +
      '[C]<qrcode size=\'20\'>http://www.developpeur-web.dantsu.com/</qrcode>';

    var data = {
      type: 'tcp',
      id: '192.168.1.99:9100',
      address: '192.168.1.99',
      port: '9100',
      mmFeedPaper: 200,
      dotsFeedPaper: 20,
      text: text
    };
    ThermalPrinter.printFormattedTextAndCut(data, function() {
      console.log('IMPRESO CORRECTAMENTE');
    }, function() {
      console.log('EROORRRR AL IMPRIMIR');
    });
  }
}
```

**But as I said:** I'll add some examples soon❗
